version: '3.8'

services:
  telegram-bot-api:
    build: .
    container_name: tg-bot-api
    restart: unless-stopped
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_LOCAL=true
      - TELEGRAM_STAT=true
      - PORT=8081
    ports:
      - "8081:8081"
    volumes:
      - tg_data:/var/lib/telegram-bot-api

volumes:
  tg_data:
